const $ = id => document.getElementById(id);
const names = {wait:'停留',reach:'接近',press:'按压',move:'移动',grasp:'抓取',rotate:'旋转',pull:'拉动',push:'推动',release:'释放'};
const arms = {left:'左臂',right:'右臂',both:'双臂',none:'无',unknown:'未知'};
const views = {head_rgb:'头部 · 左',head_right_rgb:'头部 · 右',left_wrist_rgb:'左腕',right_wrist_rgb:'右腕'};
let catalog=[], meta, doc=null, selected=0, current=0, revision=null, source='automatic', saved='', history=[], future=[], playing=false, timer=null, frameToken=0, pollTimer=null, jobEpisode=null;
let toastTimer;
function toast(text,error=false){$('toast').textContent=text;$('toast').classList.toggle('error',error);$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,5000);}
async function api(url,options={}){const r=await fetch(url,{...options,headers:{'Content-Type':'application/json',...options.headers}});const data=await r.json();if(!r.ok)throw Error(typeof data.detail==='string'?data.detail:'请求未成功，请检查输入');return data;}
function option(value,text){const el=document.createElement('option');el.value=value;el.textContent=text;return el;}
Object.entries(names).forEach(([v,t])=>$('skill').append(option(v,t+' · '+v)));
Object.entries(arms).forEach(([v,t])=>$('arm').append(option(v,t)));
Object.entries(views).forEach(([key,label])=>{const box=document.createElement('div');box.className='view';const img=document.createElement('img');img.id='view-'+key;img.alt=label+'视角';img.addEventListener('dblclick',()=>{$('zoomImage').src=img.src;$('zoomImage').alt=label+' · 帧 '+current;$('zoomDialog').showModal();});const tag=document.createElement('span');tag.className='view-label';tag.textContent=label;const frame=document.createElement('span');frame.className='view-frame';frame.id='label-'+key;box.append(img,tag,frame);$('views').append(box);});
const attrNames={colors:'颜色',shapes:'形状',materials:'材质',sizes:'尺寸',others:'其他'};
Object.entries(attrNames).forEach(([key,label])=>{const l=document.createElement('label');l.textContent=label+'（用逗号分隔）';const input=document.createElement('input');input.id='attr-'+key;input.addEventListener('change',()=>edit(d=>{d.subtasks[selected].target_object_attribute[key]=input.value.split(/[,，]/).map(s=>s.trim()).filter(Boolean);return d;}));l.append(input);$('attributes').append(l);});
function dirty(){return doc&&JSON.stringify(doc)!==saved;}
function status(){$('dirty').textContent=dirty()?'● 未保存修改':'';$('source').textContent=source==='manual'?'人工修订 · 可继续复核':'自动结果 · 待复核';$('source').className='badge '+(source==='manual'?'manual':'');$('save').disabled=!doc||!dirty();$('export').disabled=!doc;$('undo').disabled=!history.length;$('redo').disabled=!future.length;}
function commit(value){if(JSON.stringify(value)===JSON.stringify(doc))return;history.push(Editor.clone(doc));if(history.length>100)history.shift();future=[];doc=Editor.normalize(value,meta.fps);render();}
function edit(fn){if(!doc)return;try{commit(fn(Editor.clone(doc)));}catch(e){toast(e.message,true);renderInspector();}}
function renderInspector(){const s=doc?.subtasks[selected];$('empty').hidden=!!s;$('editor').hidden=!s;if(!s)return;$('selectedId').textContent='SUBTASK '+String(s.id).padStart(2,'0');$('selectedDuration').textContent=(s.end_frame-s.start_frame+1)+' 帧';for(const [id,key] of Object.entries({action:'standard_action_text',skill:'skill_id',arm:'arm_used',start:'start_frame',end:'end_frame',notes:'notes'}))$(id).value=s[key];$('start').disabled=selected===0;$('setStart').disabled=selected===0;$('end').disabled=selected===doc.subtasks.length-1;$('setEnd').disabled=selected===doc.subtasks.length-1;$('merge').disabled=selected===doc.subtasks.length-1;$('targetName').value=s.target_object_attribute.name;$('targetDescription').value=s.target_object_attribute.description;Object.keys(attrNames).forEach(k=>$('attr-'+k).value=s.target_object_attribute[k].join('，'));}
function selectSegment(i,jump=true){selected=i;render();if(jump)setFrame(doc.subtasks[i].start_frame);}
function render(){selected=Math.max(0,Math.min(selected,(doc?.subtasks.length||1)-1));$('segments').replaceChildren();$('timeline').replaceChildren();if(doc){$('count').textContent=doc.subtasks.length+' 个子任务';doc.subtasks.forEach((s,i)=>{const button=document.createElement('button');button.className=s.skill_id+(i===selected?' selected':'');button.style.flex=String(s.end_frame-s.start_frame+1);button.title=`${names[s.skill_id]} · ${s.start_frame}–${s.end_frame}`;button.setAttribute('aria-label',`子任务 ${s.id} ${button.title}`);button.textContent=s.id;button.onclick=()=>selectSegment(i);$('timeline').append(button);const row=document.createElement('tr');row.className=i===selected?'selected':'';row.tabIndex=0;row.onclick=()=>selectSegment(i);row.onkeydown=e=>{if(e.key==='Enter')selectSegment(i);};[String(s.id).padStart(2,'0'),s.standard_action_text,'',s.start_frame+' — '+s.end_frame,s.start_time.toFixed(2)+' — '+s.end_time.toFixed(2),s.end_frame-s.start_frame+1].forEach((text,j)=>{const td=document.createElement('td');td.textContent=text;td.className=j===1?'row-action':'mono';if(j===2){const tag=document.createElement('span');tag.className='skill-tag '+s.skill_id;tag.textContent=names[s.skill_id];const arm=document.createElement('span');arm.className='arm-label';arm.textContent=arms[s.arm_used];td.append(tag,arm);}row.append(td);});$('segments').append(row);});}else{$('count').textContent='暂无子任务';}renderInspector();status();markFrame();}
function markFrame(){$('frame').value=current;$('scrub').value=current;$('time').textContent=(current/meta.fps).toFixed(3)+' s';[...$('timeline').children].forEach((el,i)=>{const s=doc.subtasks[i];el.classList.toggle('active',s.start_frame<=current&&current<=s.end_frame);});}
async function setFrame(n){if(!meta)return;const target=Math.max(0,Math.min(meta.frames-1,Math.round(Number(n)||0)));const token=++frameToken;const ep=meta.id;$('viewStatus').textContent='加载帧 '+target;try{const loaded=await Promise.all(Object.keys(views).map(key=>new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve([key,img.src]);img.onerror=()=>reject(Error('帧图像未就绪，请运行自动划分准备图像'));img.src=`/api/episodes/${ep}/frames/${key}/${target}`;})));if(token!==frameToken)return;loaded.forEach(([key,url])=>{$('view-'+key).src=url;$('label-'+key).textContent=String(target).padStart(6,'0');});current=target;markFrame();$('viewStatus').textContent='原始帧 '+String(current).padStart(6,'0')+' · 4 VIEWS';}catch(e){if(token===frameToken){pause();$('viewStatus').textContent='画面未就绪';toast(e.message,true);}}}
function pause(){playing=false;clearTimeout(timer);$('play').textContent='▶';}
async function tick(){if(!playing)return;const started=performance.now();await setFrame(current+1);if(current>=meta.frames-1){pause();return;}if(playing)timer=setTimeout(tick,Math.max(0,1000/meta.fps/Number($('speed').value)-(performance.now()-started)));}
function togglePlay(){if(playing){pause();return;}if(current>=meta.frames-1){setFrame(0).then(()=>{playing=true;$('play').textContent='Ⅱ';timer=setTimeout(tick,1000/meta.fps);});}else{playing=true;$('play').textContent='Ⅱ';tick();}}
async function load(ep,which='latest'){pause();meta=catalog.find(e=>e.id===ep);$('episode').value=ep;$('meta').textContent=`${meta.frames} FRAMES / ${meta.fps} FPS / ${(meta.frames/meta.fps).toFixed(2)} s`;$('frame').max=$('scrub').max=meta.frames-1;$('lastFrame').textContent='/ '+(meta.frames-1);$('midFrame').textContent=Math.floor((meta.frames-1)/2);$('endFrame').textContent=meta.frames-1;try{const data=await api(`/api/episodes/${ep}/annotation?source=${which}`);doc=data.annotation;revision=data.revision;source=data.source;}catch(e){doc=null;revision=null;source='automatic';toast(e.message,true);}selected=0;history=[];future=[];saved=JSON.stringify(doc);render();await setFrame(0);}
async function safeLoad(ep,which){if(dirty()){const discard=await new Promise(resolve=>{const dialog=$('discardDialog');dialog.returnValue='keep';$('keepDraft').onclick=()=>dialog.close('keep');$('discardDraft').onclick=()=>dialog.close('discard');dialog.addEventListener('close',()=>resolve(dialog.returnValue==='discard'),{once:true});dialog.showModal();});if(!discard)return false;}await load(ep,which);return true;}
$('episode').onchange=async e=>{const previous=meta.id;if(!await safeLoad(e.target.value,'latest'))$('episode').value=previous;};
$('reload').onclick=()=>safeLoad(meta.id,'automatic');
$('back').onclick=()=>{pause();setFrame(current-1);};$('forward').onclick=()=>{pause();setFrame(current+1);};$('back10').onclick=()=>{pause();setFrame(current-10);};$('forward10').onclick=()=>{pause();setFrame(current+10);};$('play').onclick=togglePlay;$('frame').onchange=e=>{pause();setFrame(e.target.value);};$('scrub').oninput=e=>{pause();setFrame(e.target.value);};
for(const [id,key] of Object.entries({action:'standard_action_text',skill:'skill_id',arm:'arm_used',notes:'notes'}))$(id).onchange=()=>edit(d=>{d.subtasks[selected][key]=$(id).value;return d;});
for(const edge of ['start','end'])$(edge).onchange=()=>edit(d=>Editor.boundary(d,selected,edge,Number($(edge).value)));
$('setStart').onclick=()=>edit(d=>Editor.boundary(d,selected,'start',current));$('setEnd').onclick=()=>edit(d=>Editor.boundary(d,selected,'end',current));
$('split').onclick=()=>{edit(d=>Editor.split(d,selected,current));};$('merge').onclick=()=>{if(selected<doc.subtasks.length-1){edit(d=>Editor.merge(d,selected));toast('已合并，保留前段动作和属性；可撤销');}};
for(const [id,key] of Object.entries({targetName:'name',targetDescription:'description'}))$(id).onchange=()=>edit(d=>{d.subtasks[selected].target_object_attribute[key]=$(id).value;return d;});
$('undo').onclick=()=>{if(history.length){future.push(Editor.clone(doc));doc=history.pop();render();}};$('redo').onclick=()=>{if(future.length){history.push(Editor.clone(doc));doc=future.pop();render();}};
$('save').onclick=async()=>{const snapshot=Editor.clone(doc),ep=meta.id;try{const data=await api(`/api/episodes/${ep}/annotation`,{method:'PUT',body:JSON.stringify({annotation:snapshot,revision})});if(meta.id===ep){revision=data.revision;saved=JSON.stringify(data.annotation);source='manual';status();}toast('人工修订已保存，自动结果保留');}catch(e){toast(e.message,true);}};
$('export').onclick=()=>{if(!doc)return;const blob=new Blob([JSON.stringify(Editor.normalize(Editor.clone(doc),meta.fps),null,2)+'\n'],{type:'application/json;charset=utf-8'});const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=meta.id+(dirty()?'_draft':source==='manual'?'_manual':'_automatic')+'.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast(dirty()?'已导出当前草稿；本地修订尚未保存':'已导出 JSON');};
$('autoOpen').onclick=()=>{$('jobEpisode').value=meta.id;$('autoDialog').showModal();};$('cancelAuto').onclick=()=>{$('apiKey').value='';$('autoDialog').close();};$('autoDialog').addEventListener('close',()=>$('apiKey').value='');
async function poll(id){try{const job=await api('/api/jobs/'+id);$('job').hidden=false;$('jobText').textContent=job.episode+' · '+job.message;$('autoOpen').disabled=job.status==='running';$('jobLoad').hidden=job.status!=='complete';jobEpisode=job.episode;if(job.status==='running')pollTimer=setTimeout(()=>poll(id),1500);}catch(e){$('autoOpen').disabled=false;toast(e.message,true);}}
$('autoForm').onsubmit=async e=>{e.preventDefault();try{const data=await api('/api/jobs',{method:'POST',body:JSON.stringify({episode:$('jobEpisode').value,api_key:$('apiKey').value})});$('apiKey').value='';$('autoDialog').close();clearTimeout(pollTimer);poll(data.id);}catch(e){toast(e.message,true);}};
$('jobLoad').onclick=()=>safeLoad(jobEpisode,'automatic');$('closeZoom').onclick=()=>$('zoomDialog').close();
// Commit fields on blur as well: programmatic fill and IME edits may omit change.
['action','skill','arm','notes','start','end','targetName','targetDescription','frame'].forEach(id=>$(id).addEventListener('blur',()=>$(id).onchange?.({target:$(id)})));
window.addEventListener('beforeunload',e=>{if(dirty()){e.preventDefault();e.returnValue='';}});
document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)||$('autoDialog').open||$('zoomDialog').open||$('discardDialog').open)return;if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();pause();setFrame(current+(e.key==='ArrowLeft'?-1:1)*(e.shiftKey?10:1));}else if(e.code==='Space'){e.preventDefault();togglePlay();}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();$(e.shiftKey?'redo':'undo').click();}});
(async()=>{try{catalog=await api('/api/episodes');if(!catalog.length)throw Error('数据集中没有轨迹');catalog.forEach(e=>{$('episode').append(option(e.id,e.id));$('jobEpisode').append(option(e.id,e.id));});await load(catalog[0].id);const job=await api('/api/jobs/current');if(job)poll(job.id);}catch(e){toast(e.message,true);}})();
